[package]
name = "vgm-emu-sys"
version = "0.1.0"
authors = ["Dalia Coss <dc@dalia.cc>", "William D. Jones <thor0505@comcast.net>"]
edition = "2018"

[build-dependencies]
cmake = "0.1"
bindgen = "0.53.1"
